/**
 * Cántico de Fe Music
 * V12.4 — Hymn Catalog Export Service
 */

import AdminHymnService
  from './AdminHymnService.js';

const DEFAULT_FILENAME =
  'hymnCatalog.js';

function normalizeText(value = '') {
  return String(
    value ?? ''
  );
}

function normalizeStringList(value) {
  if (!Array.isArray(value)) {
    return [];
  }

  return value
    .map(item =>
      normalizeText(item).trim()
    )
    .filter(Boolean);
}

function normalizeLyrics(value) {
  if (!Array.isArray(value)) {
    return [];
  }

  return value.map(line =>
    normalizeText(line)
  );
}

function normalizeCopyright(
  value = {}
) {
  return {
    holder:
      normalizeText(
        value.holder ||
        'Cántico de Fe Music'
      ).trim(),

    license:
      normalizeText(
        value.license ||
        'Todos los derechos reservados'
      ).trim()
  };
}

function createCatalogHymn(
  hymn = {}
) {
  const audio =
    normalizeText(
      hymn.audio ||
      hymn.src
    ).trim();

  return {
    id:
      normalizeText(
        hymn.id
      ).trim(),

    title:
      normalizeText(
        hymn.title
      ).trim(),

    subtitle:
      normalizeText(
        hymn.subtitle
      ).trim(),

    category:
      normalizeText(
        hymn.category
      ).trim(),

    theme:
      normalizeText(
        hymn.theme
      ).trim(),

    scriptures:
      normalizeStringList(
        hymn.scriptures
      ),

    artist:
      normalizeText(
        hymn.artist ||
        'Cántico de Fe Music'
      ).trim(),

    audio,

    src:
      normalizeText(
        hymn.src ||
        audio
      ).trim(),

    cover:
      normalizeText(
        hymn.cover
      ).trim(),

    duration:
      normalizeText(
        hymn.duration
      ).trim(),

    description:
      normalizeText(
        hymn.description
      ).trim(),

    lyrics:
      normalizeLyrics(
        hymn.lyrics
      ),

    tags:
      normalizeStringList(
        hymn.tags
      ),

    copyright:
      normalizeCopyright(
        hymn.copyright
      )
  };
}

function serializeValue(
  value,
  indentation = 0
) {
  const space =
    ' '.repeat(indentation);

  const childSpace =
    ' '.repeat(
      indentation + 2
    );

  if (value === null) {
    return 'null';
  }

  if (
    typeof value === 'string'
  ) {
    return JSON.stringify(
      value
    );
  }

  if (
    typeof value === 'number' ||
    typeof value === 'boolean'
  ) {
    return String(value);
  }

  if (Array.isArray(value)) {
    if (!value.length) {
      return '[]';
    }

    const serializedItems =
      value.map(item =>
        `${childSpace}${serializeValue(
          item,
          indentation + 2
        )}`
      );

    return [
      '[',
      serializedItems.join(',\n'),
      `${space}]`
    ].join('\n');
  }

  if (
    typeof value === 'object'
  ) {
    const entries =
      Object.entries(value);

    if (!entries.length) {
      return '{}';
    }

    const serializedEntries =
      entries.map(
        ([key, itemValue]) => {
          return (
            `${childSpace}${key}: ` +
            serializeValue(
              itemValue,
              indentation + 2
            )
          );
        }
      );

    return [
      '{',
      serializedEntries.join(',\n'),
      `${space}}`
    ].join('\n');
  }

  return 'null';
}

function createCatalogSource(
  hymns = []
) {
  const serializedHymns =
    hymns.map(hymn =>
      `  ${serializeValue(
        hymn,
        2
      )}`
    );

  return [
    '/**',
    ' * Cántico de Fe Music',
    ' * Hymn Catalog',
    ' * Generated by Admin Studio',
    ' */',
    '',
    'export const hymnCatalog = [',
    serializedHymns.join(',\n\n'),
    '];',
    ''
  ].join('\n');
}

function downloadTextFile({
  filename,
  content,
  mimeType =
    'text/javascript;charset=utf-8'
}) {
  const blob =
    new Blob(
      [content],
      {
        type: mimeType
      }
    );

  const downloadUrl =
    URL.createObjectURL(
      blob
    );

  const link =
    document.createElement('a');

  link.href =
    downloadUrl;

  link.download =
    filename;

  document.body.appendChild(
    link
  );

  link.click();
  link.remove();

  window.setTimeout(() => {
    URL.revokeObjectURL(
      downloadUrl
    );
  }, 0);
}

const AdminHymnExportService = {
  getCatalogHymns() {
    return AdminHymnService
      .list()
      .map(createCatalogHymn);
  },

  generateSource() {
    const hymns =
      this.getCatalogHymns();

    return createCatalogSource(
      hymns
    );
  },

  getFilename() {
    return DEFAULT_FILENAME;
  },

  validate() {
    const hymns =
      this.getCatalogHymns();

    const errors = [];

    const ids =
      new Set();

    hymns.forEach(
      (hymn, index) => {
        const position =
          index + 1;

        if (!hymn.id) {
          errors.push(
            `El himno ${position} no tiene ID.`
          );
        }

        if (!hymn.title) {
          errors.push(
            `El himno ${position} no tiene título.`
          );
        }

        if (
          hymn.id &&
          ids.has(hymn.id)
        ) {
          errors.push(
            `El ID "${hymn.id}" está duplicado.`
          );
        }

        if (hymn.id) {
          ids.add(hymn.id);
        }

        if (
          hymn.audio &&
          !hymn.audio.startsWith('/')
        ) {
          errors.push(
            `"${hymn.title}" tiene una ruta de audio no válida.`
          );
        }

        if (
          hymn.cover &&
          !hymn.cover.startsWith('/')
        ) {
          errors.push(
            `"${hymn.title}" tiene una ruta de portada no válida.`
          );
        }
      }
    );

    return {
      valid:
        errors.length === 0,

      hymnCount:
        hymns.length,

      errors
    };
  },

  exportCatalog() {
    const validation =
      this.validate();

    if (!validation.valid) {
      return {
        success: false,
        filename:
          DEFAULT_FILENAME,
        hymnCount:
          validation.hymnCount,
        errors:
          validation.errors,
        message:
          'El catálogo contiene errores y no se puede exportar.'
      };
    }

    try {
      const content =
        this.generateSource();

      downloadTextFile({
        filename:
          DEFAULT_FILENAME,
        content
      });

      return {
        success: true,
        filename:
          DEFAULT_FILENAME,
        hymnCount:
          validation.hymnCount,
        errors: [],
        message:
          validation.hymnCount === 1
            ? 'Se exportó 1 himno correctamente.'
            : `Se exportaron ${validation.hymnCount} himnos correctamente.`
      };
    } catch (error) {
      console.error(
        '[AdminHymnExportService] No se pudo exportar el catálogo:',
        error
      );

      return {
        success: false,
        filename:
          DEFAULT_FILENAME,
        hymnCount:
          validation.hymnCount,
        errors: [
          error?.message ||
          'Error desconocido'
        ],
        message:
          'No se pudo generar el archivo hymnCatalog.js.'
      };
    }
  },

  exportJsonBackup() {
    try {
      const payload = {
        application:
          'Cántico de Fe Music',

        module:
          'Admin Hymn Manager',

        version: 1,

        exportedAt:
          new Date().toISOString(),

        hymns:
          this.getCatalogHymns()
      };

      const content =
        JSON.stringify(
          payload,
          null,
          2
        );

      const filename =
        `cantico-hymns-backup-${
          new Date()
            .toISOString()
            .slice(0, 10)
        }.json`;

      downloadTextFile({
        filename,
        content,
        mimeType:
          'application/json;charset=utf-8'
      });

      return {
        success: true,
        filename,
        hymnCount:
          payload.hymns.length,
        message:
          'La copia de seguridad JSON fue exportada correctamente.'
      };
    } catch (error) {
      console.error(
        '[AdminHymnExportService] No se pudo exportar el respaldo:',
        error
      );

      return {
        success: false,
        filename: null,
        hymnCount: 0,
        message:
          'No se pudo exportar la copia de seguridad.'
      };
    }
  }
};

export {
  DEFAULT_FILENAME,
  createCatalogHymn,
  createCatalogSource
};

export default AdminHymnExportService;
