export const configSchema = Object.freeze({
  "app.name": "string",
  "app.version": "string",
  "app.environment": ["development", "staging", "production"],
  "app.language": "string",
  "app.debug": "boolean",
  "routes.mode": ["history", "hash", "memory"],
  "routes.basePath": "string",
  "routes.notFoundPath": "string",
  "modules.autoLoad": "boolean",
  "modules.lazyLoad": "boolean",
  "modules.registryPath": "string",
  "events.enabled": "boolean",
  "events.maxListeners": "number",
  "events.logEvents": "boolean",
  "state.persist": "boolean",
  "state.storageKey": "string",
  "state.storageDriver": ["localStorage", "sessionStorage", "memory"],
  "ui.theme": ["light", "dark", "system"],
  "ui.accentColor": "string",
  "ui.animations": "boolean",
  "security.freezeConfig": "boolean",
  "security.allowRuntimeOverride": "boolean"
});
