
import { musicSchema } from "/assets/js/utils/seo.js";
import { buildHymnFromForm, exportJSON, validateLibrary } from "/assets/js/services/adminService.js";
import { seoScore, generateMetaTags } from "/assets/js/services/seoService.js";
function tabScript(){document.querySelectorAll(".admin-tab").forEach(btn=>{btn.onclick=()=>{document.querySelectorAll(".admin-tab").forEach(b=>b.classList.remove("active"));document.querySelectorAll(".admin-section").forEach(s=>s.classList.remove("active"));btn.classList.add("active");document.querySelector(`#${btn.dataset.tab}`).classList.add("active")}})}
function renderValidation(results){return results.map(r=>{const cls=r.errors.length?"status-bad":(r.warnings.length?"status-warn":"status-good");const msg=r.errors.length?r.errors.join(" "):(r.warnings.length?r.warnings.join(" "):"Correcto");return `<div class="validation-item"><span class="status-pill ${cls}">${r.hymn.title}</span><p class="muted" style="margin:8px 0 0">${msg}</p></div>`}).join("")}
export function renderAdmin(data){
 setTimeout(()=>{tabScript();const form=document.querySelector("#adminForm"),jsonPreview=document.querySelector("#jsonPreview"),schemaPreview=document.querySelector("#schemaPreview"),metaPreview=document.querySelector("#metaPreview"),idInput=document.querySelector("#hymnId"),titleInput=document.querySelector("#title");const update=()=>{if(!idInput.value&&titleInput.value){const id=titleInput.value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"");idInput.value=id;document.querySelector("#cover").value="/assets/img/covers/"+id+".jpg";document.querySelector("#audioUrl").value="/assets/audio/"+id+".mp3"}const h=buildHymnFromForm();jsonPreview.textContent=JSON.stringify(h,null,2);schemaPreview.textContent=JSON.stringify(musicSchema(h,data.settings.siteUrl),null,2);metaPreview.textContent=generateMetaTags(h,data.settings.siteUrl)};form.querySelectorAll("input,textarea,select").forEach(el=>el.addEventListener("input",update));form.querySelectorAll("input[type=checkbox]").forEach(el=>el.addEventListener("change",update));document.querySelector("#copyJson").onclick=async()=>{await navigator.clipboard.writeText(jsonPreview.textContent);alert("JSON copiado")};document.querySelector("#copySchema").onclick=async()=>{await navigator.clipboard.writeText(schemaPreview.textContent);alert("Schema copiado")};document.querySelector("#exportSeo").onclick=()=>exportJSON("seo.json",data.seo);document.querySelector("#validateLibrary").onclick=()=>{document.querySelector("#validationResults").innerHTML=renderValidation(validateLibrary(data.hymns))};document.querySelector("#seoResults").innerHTML=data.hymns.map(h=>{const s=seoScore(h);return `<div class="validation-item"><span class="status-pill ${s.score>=80?'status-good':s.score>=55?'status-warn':'status-bad'}">${s.score}</span> ${h.title}</div>`}).join("");update()});
 const themes=[...new Set(data.hymns.map(h=>h.theme))];
 return `<section class="section"><div class="container"><div class="section-head"><h2>Admin V6.5</h2><p>Admin con SEO avanzado, Schema, meta tags y validación.</p></div><div class="admin-tabs"><button class="admin-tab active" data-tab="newHymn">Nuevo Himno</button><button class="admin-tab" data-tab="seoTab">SEO</button><button class="admin-tab" data-tab="validate">Validar</button></div>
 <section class="admin-section active" id="newHymn"><div class="admin-shell"><aside class="admin-nav panel"><p class="eyebrow">Nuevo himno</p><button class="btn primary">JSON + SEO</button><a class="btn" href="/?page=seo">SEO Page</a><a class="btn" href="/api/hymns.json">API Himnos</a></aside><div><div class="panel"><form id="adminForm" class="admin-form"><div class="field"><label>Título</label><input class="input" id="title" placeholder="Fe que Mueve Montañas"></div><div class="field"><label>ID automático</label><input class="input" id="hymnId"></div><div class="field"><label>Subtítulo</label><input class="input" id="subtitle"></div><div class="field"><label>Tema</label><select id="theme">${themes.map(t=>`<option>${t}</option>`).join("")}<option>Adoración</option><option>Gratitud</option></select></div><div class="field"><label>Autor</label><input class="input" id="author" value="Cántico de Fe Music"></div><div class="field"><label>Año</label><input class="input" id="year" value="2026"></div><div class="field"><label>Duración</label><input class="input" id="duration" placeholder="4:32"></div><div class="field"><label>Referencia bíblica</label><input class="input" id="reference" placeholder="Mateo 17:20"></div><div class="field"><label>Álbum</label><input class="input" id="album"></div><div class="field"><label>Playlists</label><input class="input" id="playlists"></div><div class="field"><label>Tags/Keywords</label><input class="input" id="tags"></div><div class="field"><label>Portada</label><input class="input" id="cover"></div><div class="field"><label>Audio MP3</label><input class="input" id="audioUrl"></div><div class="field"><label>YouTube</label><input class="input" id="youtubeUrl"></div><div class="field full"><label>Descripción SEO</label><textarea id="description" rows="3"></textarea></div><div class="field full"><label>Letra</label><textarea id="lyrics" rows="10"></textarea></div><label><input type="checkbox" id="featured"> Destacado</label><label><input type="checkbox" id="popular"> Popular</label></form></div><div class="featured" style="margin-top:24px"><div class="panel"><p class="eyebrow">Schema.org</p><pre id="schemaPreview" class="admin-preview"></pre><button class="btn" id="copySchema">Copiar Schema</button></div><div class="panel"><p class="eyebrow">JSON generado</p><pre id="jsonPreview" class="admin-preview"></pre><button class="btn primary" id="copyJson">Copiar JSON</button></div></div></div></div></section>
 <section class="admin-section" id="seoTab"><div class="featured"><div class="panel"><p class="eyebrow">SEO Scores</p><div id="seoResults"></div><button class="btn primary" id="exportSeo" style="margin-top:16px">Exportar seo.json</button></div><div class="panel"><p class="eyebrow">Meta tags generados</p><pre id="metaPreview" class="admin-preview"></pre></div></div></section>
 <section class="admin-section" id="validate"><div class="panel"><p class="eyebrow">Validar biblioteca</p><button class="btn primary" id="validateLibrary">Validar ahora</button><div id="validationResults" class="validation-list"></div></div></section>
 </div></section>`;
}
